# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    body_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

body_controller:
  ros__parameters:
    joints:
      - base_rotation
      - link1_pitch
      - link2_pitch
      - bevel_pitch
      - bevel_roll
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity